"""Grandstream Home API - Python library for Grandstream devices."""

from grandstream_home_api.const import (
    ACCEPT_JSON,
    ACCESS_TOKEN_TTL,
    CONTENT_TYPE_FORM,
    CONTENT_TYPE_JSON,
    DEFAULT_HTTP_PORT,
    DEFAULT_HTTPS_PORT,
    DEFAULT_PORT,
    DEFAULT_RTSP_PORT,
    DEFAULT_USERNAME,
    DEVICE_TYPE_GDS,
    DEVICE_TYPE_GNS_NAS,
    DOOR_ACTION_LOCK,
    DOOR_ACTION_UNLOCK,
    GDS_TIMEOUT_CONNECT,
    GDS_TIMEOUT_READ,
    GDS_TIMEOUT_SOCKET_CHECK,
    GNS_DEFAULT_TIMEOUT,
    HEADER_AUTHORIZATION,
    HEADER_CONTENT_TYPE,
    HTTP_METHOD_GET,
    HTTP_METHOD_POST,
    INTEGRATION_VERSION,
    UNLOCK_CODE_AUTH_FAILED,
    UNLOCK_CODE_CHALLENGE_INVALID,
    UNLOCK_CODE_MATERIAL_EMPTY,
    UNLOCK_CODE_PERMISSION_DENIED,
    UNLOCK_CODE_SUCCESS,
    UNLOCK_CODE_TIMESTAMP_EXPIRED,
)
from grandstream_home_api.error import (
    GrandstreamAuthTokenError,
    GrandstreamChallengeError,
    GrandstreamError,
    GrandstreamHAControlDisabledError,
    GrandstreamLoginError,
    GrandstreamRTSPError,
    GrandstreamSignatureError,
    GrandstreamUnlockError,
)
from grandstream_home_api.gds import GDSPhoneAPI
from grandstream_home_api.gns import GNSNasAPI
from grandstream_home_api.utils import format_host_url, mask_sensitive_data

__all__ = [
    # API classes
    "GDSPhoneAPI",
    "GNSNasAPI",
    # Exceptions
    "GrandstreamError",
    "GrandstreamLoginError",
    "GrandstreamAuthTokenError",
    "GrandstreamChallengeError",
    "GrandstreamHAControlDisabledError",
    "GrandstreamRTSPError",
    "GrandstreamSignatureError",
    "GrandstreamUnlockError",
    # Utilities
    "format_host_url",
    "mask_sensitive_data",
    # Constants
    "ACCEPT_JSON",
    "ACCESS_TOKEN_TTL",
    "CONTENT_TYPE_FORM",
    "CONTENT_TYPE_JSON",
    "DEFAULT_HTTP_PORT",
    "DEFAULT_HTTPS_PORT",
    "DEFAULT_PORT",
    "DEFAULT_RTSP_PORT",
    "DEFAULT_USERNAME",
    "DEVICE_TYPE_GDS",
    "DEVICE_TYPE_GNS_NAS",
    "DOOR_ACTION_LOCK",
    "DOOR_ACTION_UNLOCK",
    "GDS_TIMEOUT_CONNECT",
    "GDS_TIMEOUT_READ",
    "GDS_TIMEOUT_SOCKET_CHECK",
    "GNS_DEFAULT_TIMEOUT",
    "HEADER_AUTHORIZATION",
    "HEADER_CONTENT_TYPE",
    "HTTP_METHOD_GET",
    "HTTP_METHOD_POST",
    "INTEGRATION_VERSION",
    "UNLOCK_CODE_AUTH_FAILED",
    "UNLOCK_CODE_CHALLENGE_INVALID",
    "UNLOCK_CODE_MATERIAL_EMPTY",
    "UNLOCK_CODE_PERMISSION_DENIED",
    "UNLOCK_CODE_SUCCESS",
    "UNLOCK_CODE_TIMESTAMP_EXPIRED",
]
